import { readFileSync } from 'node:fs';
import { baseSepolia } from 'viem/chains';
import type { Address } from 'viem';

import { makeChainClient, type Deployment } from './anvil.ts';
import type { ChainClient } from '../runner.ts';
import type { Addresses } from '../agents/roster.ts';

/**
 * The Base Sepolia client, for the L3 campaign.
 *
 * It differs from the Anvil client in exactly two respects: the chain, and
 * where the signing keys come from. Everything else — how a plan becomes
 * calldata, how an outcome is graded, how the shadow ledger is compared —
 * is the chain-agnostic code both share, which is the whole reason that code
 * was written to take its keys as a parameter.
 *
 * The keys are read from `.sim-keys.json` at run time, on the operator's own
 * machine, and never appear in source, in a log, or in a finding. That file is
 * gitignored and mode 600 by the generator; this module reads it, hands the
 * values straight to viem, and holds no other copy. Nothing here prints a key,
 * not even a truncated one — a key half-shown is a key shown.
 */

/** The shape of one account in the secret file. Only these fields are read. */
interface SecretAccount {
  id: string;
  address: Address;
  privateKey: `0x${string}`;
}

interface SecretFile {
  mnemonicFingerprint?: string;
  accounts: SecretAccount[];
}

/**
 * Loads the signing keys from the secret file.
 *
 * Returns them as an array for viem, and does nothing else with them. The one
 * validation is structural — that each entry has a well-formed key — because a
 * malformed key should stop the run with a clear message rather than fail
 * opaquely deep inside a signer. The message names the account id, never the
 * value.
 */
export function loadSimKeys(secretPath: string): `0x${string}`[] {
  let parsed: SecretFile;
  try {
    parsed = JSON.parse(readFileSync(secretPath, 'utf8')) as SecretFile;
  } catch (e) {
    throw new Error(
      `Could not read the secret key file at ${secretPath}: ${e instanceof Error ? e.message : String(e)}. ` +
        `It is generated by gen-sim-wallets.mjs and lives only on the operator's machine.`,
    );
  }

  if (!Array.isArray(parsed.accounts) || parsed.accounts.length === 0) {
    throw new Error(`The secret key file at ${secretPath} has no accounts.`);
  }

  const keys: `0x${string}`[] = [];
  for (const account of parsed.accounts) {
    if (!/^0x[0-9a-fA-F]{64}$/.test(account.privateKey ?? '')) {
      // The id, not the key: a malformed secret is still a secret.
      throw new Error(`Account "${account.id}" in the secret file has a malformed private key.`);
    }
    keys.push(account.privateKey);
  }
  return keys;
}

/**
 * Optional fingerprint check: confirms the secret file and the public key map
 * came from the same seed before a single transaction is sent.
 *
 * A key map paired with the wrong secret would sign as the wrong addresses, and
 * every action would be refused for lack of a role — a whole campaign of false
 * findings that this one comparison prevents. The fingerprint is public and
 * reveals nothing about the seed.
 */
export function assertSeedMatches(secretPath: string, expectedFingerprint: string): void {
  const parsed = JSON.parse(readFileSync(secretPath, 'utf8')) as SecretFile;
  if (parsed.mnemonicFingerprint && parsed.mnemonicFingerprint !== expectedFingerprint) {
    throw new Error(
      `The secret file's seed fingerprint (${parsed.mnemonicFingerprint}) does not match the key map ` +
        `(${expectedFingerprint}). They are from different seeds; signing would use the wrong addresses.`,
    );
  }
}

/**
 * Builds the staging client.
 *
 * The chain guard inside `runScenario` still runs and still restricts writes to
 * the permitted chains — Base Sepolia is one of them, mainnet is not. This
 * function does not repeat that guard, but it is the natural place someone would
 * later point at a production RPC, which is exactly why the guard lives at the
 * top of the run and not here.
 */
export function makeStagingClient(
  rpcUrl: string,
  dep: Deployment,
  addr: Addresses,
  lpTarget: Address,
  keys: readonly `0x${string}`[],
): ChainClient {
  return makeChainClient(rpcUrl, dep, addr, lpTarget, { keys, chain: baseSepolia });
}
